kind: Service
apiVersion: v1
metadata:
  name: doneill-echo-reply
  namespace: doneill
  labels:
    tier: seneca-services
spec:
  selector:
    srv: echo-reply
  ports:
  - port: 39998
    name: mesh-listen
  - port: 39997
    name: mesh
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: doneill-echo-reply8
  namespace: doneill
spec:
  replicas: 1
  selector:
    matchLabels:
      srv: echo-reply
  template:
    metadata:
      labels:
        srv: echo-reply
    spec:
      containers:
      - name: echo-reply
        image: doneill/echo-reply:v14
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 39998
          name: mesh-listen
        - containerPort: 39997
          name: mesh